OnlineOrder/Models/Advertisement.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Key { get; set; }
        public string Description { get; set; }
    }
}

OnlineOrder/Areas/Admin/Controllers/AdvertisementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineOrder;
using OnlineOrder.Models;
using PagedList;

namespace OnlineOrder.Areas.Admin.Controllers
{
    public class AdvertisementsController : Controller
    {
        private OnlineOrdersEntities db = new OnlineOrdersEntities();

        // GET: Admin/Advertisements
        public ActionResult Index(int? page, string searchString)
        {
            // 1. Tham số int? dùng để thể hiện null và kiểu int
            // page có thể có giá trị là null và kiểu int.
            // 2. Nếu page = null thì đặt lại là 1.
            if (page == null) page = 1;
            // 3. Tạo truy vấn, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy theo ID mới có thể phân trang.
            var links = (from l in db.Advertisements select l).OrderBy(x => x.Id);
            // 4. Tạo kích thước trang (pageSize) hay là số Link hiển thị trên 1 trang
            int pageSize = 2;
            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);
            if (searchString != null)
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    //tạo truy vấn theo trường Key có chứa chuỗi searchString 
                    links = (IOrderedQueryable<Advertisement>)links.Where(s => s.Key.Contains(searchString));
                }
                return View(links.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return View(links.ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: Admin/Advertisements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = db.Advertisements.Find(id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
            return View(advertisement);
        }

        // GET: Admin/Advertisements/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Advertisements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Key,Description")] Advertisement advertisement, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                string fileName = System.IO.Path.GetFileName(image.FileName);
                //stored image
                string urlImage = Server.MapPath("~/ImageStored/Advertisements/" + fileName);
                image.SaveAs(urlImage);
                //url
                advertisement.Image = "~/ImageStored/Advertisements/" + fileName;
                if (ModelState.IsValid)
                {
                    db.Advertisements.Add(advertisement);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewBag.Message = "You have not specified a file.";
                ViewBag.Color = "red";
                return View("Create");
            }
            return View(advertisement);
        }

        // GET: Admin/Advertisements/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = db.Advertisements.Find(id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
            return View(advertisement);
        }

        // POST: Admin/Advertisements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Key,Description")] Advertisement advertisement, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                string fileName = System.IO.Path.GetFileName(image.FileName);
                //stored image
                string urlImage = Server.MapPath("~/ImageStored/Advertisements/" + fileName);
                image.SaveAs(urlImage);
                //url
                advertisement.Image = "~/ImageStored/Advertisements/" + fileName;
                if (ModelState.IsValid)
                {
                    db.Entry(advertisement).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewBag.Message = "You have not specified a file.";
                ViewBag.Color = "red";
                return View("Edit");
            }
            return View(advertisement);
        }

        // GET: Admin/Advertisements/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = db.Advertisements.Find(id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
            return View(advertisement);
        }

        // POST: Admin/Advertisements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Advertisement advertisement = db.Advertisements.Find(id);
            db.Advertisements.Remove(advertisement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineOrder/Areas/Admin/Views/Advertisements/Create.cshtml
@model OnlineOrder.Models.Advertisement

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/MainLayoutAdmin.cshtml";
}

<section class="content">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Create new advertisement</h2>
        </div>
        @using (Html.BeginForm("Create", "Advertisements", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="panel-body">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Choose a Image</label>
                            <div class="input-group">
                                <input type="file" name="Image" id="Image" accept="image/*" />
                                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                                <div class="text-danger">@ViewBag.Message</div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Sort</label>
                            @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Description</label>
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel-footer">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    </div>
</section>

OnlineOrder/Areas/Admin/Views/Advertisements/Delete.cshtml
@model OnlineOrder.Models.Advertisement

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/MainLayoutAdmin.cshtml";
}

<section class="content">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Are you sure you want to delete this?</h2>
        </div>
        <div class="panel-heading">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Image)
                </dt>

                <dd>
                    <img src="@Url.Content(Model.Image)" alt="@Model.Image" style="width:130px;" />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Key)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Key)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
        </div>
        <div class="panel-footer">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <input type="submit" value="Delete" class="btn btn-danger" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
            }
        </div>
    </div>
</section>

OnlineOrder/Areas/Admin/Views/Advertisements/Details.cshtml
@model OnlineOrder.Models.Advertisement

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/MainLayoutAdmin.cshtml";
}

<section class="content">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Details</h2>
        </div>
        <div class="panel-heading">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Image)
                </dt>

                <dd>
                    <img src="@Url.Content(Model.Image)" alt="@Model.Image" style="width:130px;" />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Key)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Key)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
</section>

OnlineOrder/Areas/Admin/Views/Advertisements/Edit.cshtml
@model OnlineOrder.Models.Advertisement

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/MainLayoutAdmin.cshtml";
}

<section class="content">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Edit Advertisement</h2>
        </div>
        @using (Html.BeginForm("Edit", "Advertisements", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="panel-body">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Choose a Image</label>
                            <div class="input-group">
                                <input type="file" name="Image" id="Image" accept="image/*" />
                                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                                <div class="text-danger">@ViewBag.Message</div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Sort</label>
                            @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Description</label>
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel-footer">
                <input type="submit" value="Update" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    </div>
</section>

OnlineOrder/Areas/Admin/Views/Advertisements/Index.cshtml
@model PagedList.PagedList<OnlineOrder.Models.Advertisement>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/MainLayoutAdmin.cshtml";
}
<section class="content">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-7">
                    <h2>Advertisements</h2>
                </div>
                <div class="col-md-4">
                    <form class="input-form" role="form">
                        <div class="input-group">
                            @using (Html.BeginForm("Index", "Advertisements", FormMethod.Get)) // -- phần thay đổi
                            {
                                <div class="input-group-append">
                                    @Html.TextBox("SearchString", null, new { @placeholder = "Search...", @class = "form-control" })
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            }
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <table class="table">
            <tr>
                <th style="width:130px;">
                    <label>Image</label>
                </th>
                <th>
                    <label>Key</label>
                </th>
                <th>
                    <label>Description</label>
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src="@Url.Content(item.Image)" alt="Alternate Text" style="width:130px;" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Key)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td style="width:60px">
                        <a href="@Url.Action("Details","Advertisements", new { id = item.Id })" class="btn btn-default fa fa-search"></a><br />
                        <a href="@Url.Action("Edit", "Advertisements", new { id = item.Id})" class="btn btn-success fa fa-edit"></a><br />
                        <a href="@Url.Action("Delete", "Advertisements", new { id = item.Id })" class="btn btn-danger fa fa-trash"></a>
                    </td>
                </tr>
            }

        </table>
        <div class="panel-footer">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>
    </div>
</section>